name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Lancer les tests
        env: 
          PYTHONPATH: ./src
        run: |
          pytest

  deploy:
    needs: build
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: vm-code
    steps:
      - name: Déployer via SSH (avec mot de passe)
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e
            # 1) Cloner si inexistant, sinon pull
            if [ ! -d ~/log430-a25-labo0 ]; then
              git clone https://github.com/EricOrellanaAbrego/log430-a25-labo0.git ~/log430-a25-labo0
            fi
            cd ~/log430-a25-labo0

            # 2) Mettre à jour le code
            git pull origin main

            # 3) (Ré)installer dépendances
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -U pip
            pip install -r requirements.txt

            # 4) Préparer l'import
            export PYTHONPATH=src

            # 5) Redémarrer proprement l'app en arrière-plan
            pkill -f "python .*calculator.py" || true
            nohup python src/calculator.py >/tmp/calculator.log 2>&1 &

            # 6) Petits états utiles dans les logs
            echo "App lancée. PID(s):"; pgrep -f "python .*calculator.py" || true
            echo "Espace disque:"; df -h | head -n 5
            echo "Mémoire:"; free -h