name: example_CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Lancer les tests
        env: 
          PYTHONPATH: ./src
        run: |
          pytest

  deploy:
    needs: build
    if: success() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: vm-code
    steps:
      - name: Déployer sur le serveur distant
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            set -e

            # Pull le code 
            cd ~/log430-a25-labo0
            git pull origin main

            # Installer les requirements de nouveau
            python3 -m venv .venv
            source .venv/bin/activate
            pip install -U pip
            pip install -r requirements.txt

            # Préparer import du src
            export PYTHONPATH=src

            # Redémarrer le code
            pkill -f "python .*calculator.py" || true
            nohup python src/calculator.py >/tmp/calculator.log 2>&1 &